# ================== EUREKA SERVER PROD CONFIGURATION ==================

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# Production Stability
eureka.server.enable-self-preservation=true
